### ISSUE TITLE
Require High Redstone Signal nonfunctioning

### ISSUE THREAD

**Issue by 666lumberjack** [shadowfacts/Activator#2]
Hi,

I'm trying to set a redstone activator to require a high signal, but it doesn't appear to be working. The activator continues clicking regardless of whether it has a signal. If set to require a low signal it works properly. This seems to happen whether or not it's set to right or left click. 

Having this problem in the latest version for 1.7.10 on curseforge.

**Comment by shadowfacts** [comment]
This is fixed for 1.0.1 on CurseForge (pending approval).
